### ISSUE TITLE
Can I do an if statement with a constant?

### ISSUE THREAD

**Issue by mvmaasakkers** [feulf/raintpl3#137]
When I try to do {if="$value.from.id == #PROFILE_URL#"}from{else}to{/if} I get:

syntax error, unexpected '?>'

**Comment by mvmaasakkers** [comment]
Allright... seeing as 7 years have past I'm closing this issue now. Sorry for letting it open so long.

**Comment by feulf** [comment]
@mvmaasakkers 7 years. Wow. Well thanks for your patience :)

I moved to different things since then, and stop supporting raintpl, rainframework, and raincms. Was fun working on it though.

**Comment by prisis** [comment]
How about to archive the projects?

**Comment by mvmaasakkers** [comment]
@feulf I know, right? Same here... I was just checking my list of Github issues so I found this one and a few other which were old. Time flies...
