### ISSUE TITLE
Malfunction on compiled vars

### ISSUE THREAD

**Issue by st2cs** [feulf/raintpl3#153]
When compiling a design and depending on where a variable is set the compilation fails.
The method used is assign();

![parse-error](https://cloud.githubusercontent.com/assets/7582016/3005306/8760e230-ddd8-11e3-9013-c202a69c5fe2.jpg)
![parse-error2](https://cloud.githubusercontent.com/assets/7582016/3005305/8760c304-ddd8-11e3-8855-fd773f20ea0a.jpg)

**Comment by feulf** [comment]
@Manawyrm fixed this issue. Closing this bug.
