### ISSUE TITLE
Pass variable through include template

### ISSUE THREAD

**Issue by JmzTaylor** [feulf/raintpl3#188]
I have a loop that is generating elements on a page.  The way I was doing it was 

    <?php $id=$categories[0]; include('page.php'); ?>

Which doing it this way page.php can use the $id variable.  I will never know this value or the length of the array.  

Is there any way I can do something similar with rain?

**Comment by feulf** [comment]
Yes. You can use an {include} inside a {loop}:
https://github.com/feulf/raintpl3/wiki/Documentation-for-web-designers#loopvar
https://github.com/feulf/raintpl3/wiki/Documentation-for-web-designers#includetemplate

e.g.
```
{loop="categories"}
   {include="page"}
{/loop}
```

Inside the loop you can use `{key}` and `{value}` so inside your *page* you can do things like:
```
{$value.title}
```
