### ISSUE TITLE
Syntax error, unexpected '{'

### ISSUE THREAD

**Issue by AugustoMarcelo** [feulf/raintpl3#191]
I tried to use an if within an input as follows:
```
<input type="checkbox" class="custom-control-input" name="ativo" value="1" id="ativo" {if="$componente.ativo == 1" }checked{/if}> <label for="ativo"
                            class="custom-control-label">Ativo</label>
```
But the following error is thrown:
>  Parse error: syntax error, unexpected '}', expecting end of file in C:\wamp64\www\filarmonica\views-cache\componentes-update.aed382e698bcff2b6209ee2a3aed28b5.rtpl.php on line

**Comment by ramonribeiro96** [comment]
try to leave without space, your "if" can give problem. `{if="$ componente.ativo == 1"}`

**Comment by feulf** [comment]
Correct, you can remove the spaces and it should work:
```{if="$componente.ativo==1"}checked{/if}```

I discourage to use a template engine to build a form from the backend. A better pattern today is to separate presentation and business logic in UI and API. For example, you can create your page in React, and the form in React Form.

**Comment by AugustoMarcelo** [comment]
You're right. The space, automatically placed by VS Code, was causing the error. Thank you!

Do you have a course you can give me, Feulf?
